In [1]:
import os
os.chdir('E:\\germany\\all work directory')

## 1.Write a Python Program to Add Two Matrices?
## Answer :

In [20]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,9,1],[7,5,3]])

print('\nAddition of\n \n{}\n  \nand\n  \n{}\n  \nis\n \n{}'.format(a,b,np.add(a,b)))


Addition of
 
[[1 2 3]
 [4 5 6]]
  
and
  
[[5 9 1]
 [7 5 3]]
  
is
 
[[ 6 11  4]
 [11 10  9]]


## 2.Write a Python Program to Multiply Two Matrices?
## Answer :

In [19]:
a = np.array([[1,2,3],[4,5,6]]).T
b = np.array([[5,9,1],[7,5,3]])

print('\nMultiplication of\n \n{}\n \nand\n \n{}\n  \nis\n \n{}'.format(a,b,np.dot(a,b)))


Multiplication of
 
[[1 4]
 [2 5]
 [3 6]]
 
and
 
[[5 9 1]
 [7 5 3]]
  
is
 
[[33 29 13]
 [45 43 17]
 [57 57 21]]


## 3.Write a Python Program to Transpose a Matrix?
## Answer :

In [23]:
a = np.array([[1,2,3],[4,5,6]])
x = a.copy()
x = a.T
print("original Matrix :\n \n{}\n".format(a))
print("Matrix after transpose :\n \n{}\n".format(x))


original Matrix :
 
[[1 2 3]
 [4 5 6]]

Matrix after transpose :
 
[[1 4]
 [2 5]
 [3 6]]



## 4.Write a Python Program to Sort Words in Alphabetic Order?
## Answer :

In [28]:
## take string as a user input
st = input("Enter a string for sorting in alphabetic order : ")

## split string and make all splited string into lower case
words = [i.lower() for i in st.split()]

words.sort()

## print all word through for loop
for i in words:
    print(i)

Enter a string for sorting in alphabetic order : Kishan Harshukh Ranjan Bhavik
bhavik
harshukh
kishan
ranjan


## 5.Write a Python Program to Remove Punctuation From a String?
## Answer :

In [32]:
## mention all punctuation
p = """!~`@#$%^&*(){}[]_=:;'"<>,.?/|\ """

## User input string
st = input("Enter a String For Removing Punctuation : ")

new_string = ""

for i in st:
    if i not in p:
        new_string += i
print(new_string)





Enter a String For Removing Punctuation : kis@#$n kis&*@
kisnkis
